### ISSUE TITLE
About the train epoch

### ISSUE THREAD

**Issue by sleepyseal** [NaJaeMin92/FixBi#5]
Hello, I find that all of the total epoches, bim_start, sp_start and cr_start are equal to 100. So Bidirectional Matching and Consistency Regularization will not start in this case. Can you check the code and reply me?

**Comment by NaJaeMin92** [comment]
Hi @sleepyseal 
Thanks for your interest. 

Here are the hyperparameter settings.

```
For Office-31 and Office-Home:
total_epochs = 200
bim_start > 100
cr_start > 100
sp_start < 100
```

```
For VisDA-C:
total_epochs = 25
bim_start > 10
cr_start > 10
sp_start < 10
```
