### ISSUE TITLE
how to train when the source dataset has labels but the target doesn't

### ISSUE THREAD

**Issue by rotem154154** [NaJaeMin92/FixBi#8]
i'm trying to transfer dataset that has labels to simular dataset without labels
like in this example
https://www.youtube.com/watch?v=9d4jmPmTWmc&t=570s
[<img width="646" alt="Screen Shot 2021-10-15 at 13 59 49" src="https://user-images.githubusercontent.com/5027057/137477314-a38df5d7-b759-485d-8d93-ea66f8f73be9.png">](https://www.youtube.com/watch?v=9d4jmPmTWmc&t=570s)
from the code that load the datasets its look like both the source and target dataset supposed to have labels.
https://github.com/NaJaeMin92/FixBi/blob/3c986946fd1582cc0e59510115d5c2e1d307b412/src/dataset.py#L23

**Comment by NaJaeMin92** [comment]
Hi @rotem154154 

There's no reason to use an `ImageFolder` if you don't have any labels at all.
`ImageFolder` returns samples and labels according to the folder of each class. I used ImageFolder to access the source labels.
